baseURL = 'https://hugomg.github.io/python-ufrj'
languageCode = 'pt_BR'
title = 'Python UFRJ'
theme = 'relearn'

[markup.highlight]
    # Cor do syntax highlighting color
    # Escolha uma compatível com o themeVariant do Relearn:
    # ambos temas claros ou ambos temas escuros
    style =  'abap'

[markup.goldmark.renderer]
    # Permite incluir tags HTML como <sup></sup>
    # Também é necessário para os plugins mermaid e mathjax
    # (Tome cuidado para não incluir HTML malvado sem querer)
    unsafe = true

[params]
    # Configuração do tema (Relearn)
    # https://mcshelby.github.io/hugo-theme-relearn/basics/configuration/index.html

    # Estes parâmetros afetam tags <meta>
    author.name = 'Instituto de Computação'
    description = 'Material do curso Computação I em Python'

    # Estes parâmetros mexem em coisas visíveis
    themeVariant = 'zen-light'
    #themeVariant = 'blue'
    disableLandingPageButton = true
    disableSearch = true
    ordersectionsby = 'linktitle'
    alwaysopen = true
    highlightWrap = false # pois Python depende de identação
    disableInlineCopyToClipBoard = true
    disableHoverBlockCopyToClipBoard = false
