#baseURL = 'http://example.org/'
languageCode = 'pt_BR'
title = 'Python UFRJ'
theme = 'relearn'

[markup.goldmark.renderer]
    # Permite incluir tags HTML como <sup></sup>
    # Também é necessário para os plugins mermaid e mathjax
    # (Tome cuidado para não incluir HTML malvado sem querer)
    unsafe = true

[params]
    # Configuração do tema (Relearn)
    # https://mcshelby.github.io/hugo-theme-relearn/basics/configuration/index.html

    # Estes parametros afetam tags <meta>
    author.name = 'Instituto de Computação'
    description = 'Material do curso Computação I em Python'

    themeVariant = 'blue'
    disableSearch = true
    ordersectionsby = 'linktitle'
    alwaysopen = true
    highlightWrap = false # pois Python depende de identação
